name: main

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches: [master]

run-name: ${{ github.workflow }} | ${{ github.event.pull_request.number }} ${{ github.event.pull_request.title || github.event.head_commit.message }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: docker build --tag nix-package-versions .
      working-directory: ./

    - name: Test
      run: docker run nix-package-versions ./utils.sh test
